language: php

php:
 - "7.0"
 - "7.1"

before_script:
 - composer self-update
 - composer --version
 - composer install -n --dev --prefer-source

script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text
